### ISSUE TITLE
[peppereus] need to modify #559

### ISSUE THREAD

**Issue by kochigami** [jsk-ros-pkg/jsk_robot#1003]
- [x] need to modify srv file name (`ShowResource.srv` is not used now, instead use `SetString.srv` and `GetString.srv` ) ref: https://github.com/ros-naoqi/naoqi_bridge_msgs/pull/7 [done in #998]
- [x] add naoqi_apps branch information ref: https://github.com/ros-naoqi/naoqi_bridge/pull/52 this PR was not merged. [done in #1000]
- [x] add test  [done in #998]
