### ISSUE TITLE
pr1012,pr1040のapplicationsユーザでデモを動かせるようにする

### ISSUE THREAD

**Issue by furushchev** [jsk-ros-pkg/jsk_robot#366]
#### 条件
  - deb + jsk-ros-pkg/jsk_demosで動くのが理想的
  - kinect_head名前空間

#### 状況
以下のものは問題があるのでソースから入れています。
- [ ] `robot start`
  - [ ] jsk-ros-pkg/jsk_smart_apps
    - [ ] not released
  - [ ] PR2/app_manager
    - [x] `app_master` node not installed -> https://github.com/PR2/app_manager/pull/2
    - [x] python scripts not installed -> https://github.com/PR2/app_manager/pull/3
    - [ ] release待ち (see. https://gist.github.com/furushchev/0580d2adf129d163b05b )
  - [ ] PR2/pr2_navigation
    - [x] `self_filter` node not installed -> https://github.com/PR2/pr2_navigation/issues/18
    - [ ] https://github.com/PR2/pr2_navigation/issues/18 not released -> https://github.com/PR2/pr2_navigation/issues/19 released only `shadow_fixed`?
    - [ ] kinectが落ちる？ -> jsk_pcl_rosをソースから入れると解決（バージョンの問題？）
- [ ] `roslaunch jsk_pr2_startup pr2.launch`
  - [x] pr2/pr2_apps
    - [x] `pr2_mannequin_mode` yaml files installed to incorrect dest -> https://github.com/PR2/pr2_apps/pull/17
    - [ ] wait to release
  - [ ] jsk-ros-pkg/jsk_topic_tools
    - [x] `config` not installed -> https://github.com/jsk-ros-pkg/jsk_common/pull/1028
    - [ ] wait to release
  - [ ] SharedAutonomyToolkit/shared_autonomy_manipulation
    - [ ] `safe_teleop_base` not released -> https://github.com/SharedAutonomyToolkit/shared_autonomy_manipulation/issues/5
- [ ] `roslaunch detect_cans_in_fridge_201202 startup.launch`
  - [ ] snap_map_icp 
    - [ ] wait for release
  - [ ] jsk-ros-pkg/jsk_pr2eus
    - [ ] 缶の受け渡し動作中に止まる -> https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/151

**Comment by k-okada** [comment]
mongodb_store 関係のエラーはどうなったかな？

--
◉ Kei Okada

**Comment by garaemon** [comment]
jsk_commonはtagを切っておきました

**Comment by furushchev** [comment]
@k-okada 
> mongodb_store 関係のエラーはどうなったかな？
今はpr1040が空いていないので、pr1012で作業していますが、こちらだと問題にならないです。
そういえば前にmongodプロセスに特殊な許可を与えないと複数ユーザで同じdatabase pathを使うmongodbを立ち上げられないことを思い出したので、それを試してみます。

**Comment by furushchev** [comment]
pr1040でもmongodbが動きました。

```bash
sudo killall mongod
sudo service mongodb stop
sudo chown -R robot:users /path/to/db
sudo chmod 777 /path/to/db # http://stackoverflow.com/questions/30814288/cannot-start-mongodb-service
sudo setcap cap_fowner+ep /usr/bin/mongod # https://jira.mongodb.org/browse/SERVER-7583
```

**Comment by k-okada** [comment]
nice!, where is /path/to/db in pr2 robot

--
◉ Kei Okada

**Comment by furushchev** [comment]
@k-okada for PR2, it is /var/lib/robot/mongodb_store
(see. https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_pr2_robot/jsk_pr2_startup/pr2_bringup.launch#L165 )

**Comment by furushchev** [comment]
mongodbが新しく作ってしまうファイルの権限の問題があるようです。
https://github.com/strands-project/mongodb_store/pull/139
でLinuxデフォルトのmongodも使えるようなPRをだしました。

**Comment by furushchev** [comment]
pr1012でもデモができてきていて、openni名前空間を留めておく意味があまりないので、pr1040も標準名前空間に戻しました。

**Comment by furushchev** [comment]
hydroはEOLなのでapplicationsユーザでデモが出来るように.rosinstallでバージョンを固定しています。
