### ISSUE TITLE
Upgrade Baxter 011310P0014: v1.1.0 -> v1.2.0

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_robot#574]
## Plan
Operator: Kentaro Wada (@wkentaro)
Date: 2016-03-23 (preliminary: 2016-03-24)

## References
* http://sdk.rethinkrobotics.com/wiki/Software_Update_-_v1.2.0
* https://groups.google.com/a/rethinkrobotics.com/forum/#!msg/brr-users/Jf4dX9R_-Pk/NJEJdaqsEQAJ

## TODO
- [x] check boot of the robot
- [x] check rosparam /rethink/software_version as 1.2.0
- [x] check enable_robot.py
- [x] check tuck_arm.py
- [x] check gripper_keyboard.py
- [x] check joint control from euslisp
- [x] check gripper control from euslisp

cc: @knorth55 @k-okada

**Comment by wkentaro** [comment]
![image](https://cloud.githubusercontent.com/assets/4310419/13982613/76078410-f12e-11e5-9d1b-939ffaaf5235.jpeg)
![image](https://cloud.githubusercontent.com/assets/4310419/13982614/7652dabe-f12e-11e5-9e6b-acafa4e42652.jpeg)

**Comment by wkentaro** [comment]
![image](https://cloud.githubusercontent.com/assets/4310419/13982701/d7d37474-f12e-11e5-8192-2a0ba345da04.jpeg)

**Comment by wkentaro** [comment]
done.
